index.html
packages/did-core-test-server/suites/did-spec/default.json
packages/did-core-test-server/suites/did-spec/defaultSuiteConfig.json
packages/did-core-test-server/suites/did-spec/did-parameters.js
test-vectors/did-spec.latest.json

This is aimed at fixing #22.
- Update DID parameters to use camelCase, following https://github.com/w3c/did-core/pull/553.
- Test `versionTime` DID parameter. Update test case to use [xsd:dateTime](https://www.w3.org/TR/xmlschema11-2/#dateTime) rather than UNIX timestamp, to match DID Core.
- Check that DID parameter values are ASCII only as specified in DID Core, rather than for all possible DID parameters.
Notes/questions:
- The `versionTime` test validates the parameter with a regex based on the [lexical representation of xsd:dateTime](https://www.w3.org/TR/xmlschema11-2/#nt-dateTimeRep) with the constraints for `versionTime` applied. But the [day-of-month constraints](https://www.w3.org/TR/xmlschema11-2/#con-dateTime-dayValue) are not checked (e.g. when is February 29th a valid date). …

Test DID Parameters

---

packages/did-core-test-server/suites/did-spec/did-parameters.js

Add Section numbers to tests for DID parameters, as requested in https://github.com/w3c/did-test-suite/issues/22#issuecomment-807298139.

Organize DID Parameter tests by section

---

packages/did-core-test-server/suites/did-spec/did-metadata-structure.js
packages/did-core-test-server/suites/did-spec/did.spec.js

This PR contains on-going work for Metadata Structure tests, Issue #31.
Includes most of the tests besides one with dependency with spec registry.

DID Metadata Structure Test (first set)

---

packages/did-core-test-server/suites/did-spec/did-producer.js
packages/did-core-test-server/suites/did-spec/did.spec.js

Implement the tests needed by issue #24.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 24, 2021, 2:01 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fdid-test-suite%2F37057d1553566e0b38f2bf21e49bb3b8c0ce8373%2Findex.html%3FisPreview%3Dtrue)
```
😭  Sorry, there was an error generating the HTML. Please report this issue!
Specification: …
```

Add Producer tests for Section 1.4 and Section 6.1.

---

packages/did-core-test-server/suites/did-core-properties/did-metadata-structure.js

The Coverage of the recursive test was incorrect.
Last two statements should be outside of recursive loop.
Also fixed the recursive function's name.

Fix to Metadata Structure Test

---

packages/did-core-test-server/suites/utils.js

The function definition includes sub-seconds but the spec doesn't allow sub-seconds.
Luckily, no tests using this predicate up to now.

Fix to isXmlDatetime utility function to not allowing sub-seconds

---

packages/did-core-test-server/suites/utils.js

Allowing pct-encoded characters.
I also think `isValidDid` require anchoring at the begning and the end of string. current regexp matcher matches not only DID but also DID URL. This predicate also matches DID string in the middile of strings.
Maybe better to use isValidDid predicate and toBeValidDid matcher in `jest-did-matcher` packages.
Actually I added `^` and `$` and experimented -- raised lot of errors.
We need to adjust the tests for the purpose of the match.

Fixing regexp for util.js:isValidDid to add pct-encoded character support

---

packages/did-core-test-server/suites/did-resolution/did-resolution.js

Per discussion on the 2021-04-13 DID WG topic call, see: https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-04-13-did-topic
Partially addresses https://github.com/w3c/did-test-suite/issues/53.

Skip statements in DID Resolution that can't be tested by code.

---

packages/did-core-test-server/suites/did-core-properties/did-core-properties.js
packages/did-core-test-server/suites/did-identifier/did-parameters.js
packages/did-core-test-server/suites/did-identifier/did-syntax.js

I updated the identifier, core properties, and production suites to use @shigeya (AWESOME!!!) new jest extensions. I also tested to make sure they fail when given invalid input as I went along (and they did). I haven't removed the util.js files just yet... we need to move everything over to the new jest matchers before removing the old `util.js` test functions.

Update identifier, core properties, and production suites to use new jest extensions

---

packages/did-core-test-server/suites/did-consumption/did-consumption.spec.js
packages/did-core-test-server/suites/did-consumption/did-json-consumption.js
packages/did-core-test-server/suites/did-production/did-json-production.js
packages/did-core-test-server/suites/implementations/did-example-didwg.json

This PR adds JSON Production and Consumption tests as well as extending `did:example` in `application/did+json` format to include all possible values in the data model (datetime, integer, double, boolean, and null).

Add JSON Production and Consumption tests.

---

packages/did-core-test-server/suites/did-consumption/default.js
packages/did-core-test-server/suites/did-core-properties/default.js
packages/did-core-test-server/suites/did-identifier/default.js
packages/did-core-test-server/suites/did-production/default.js
packages/did-core-test-server/suites/implementations/did-is.json

This adds the "did:is" DID Method to the did-test-suite for the suites:
- consumption
- core-properties
- identifier
- production
In another future PR, we'll add testing of the DID Resolution.

Add "did:is" to the did-test-suite

---

packages/did-core-test-server/suites/did-consumption/default.js
packages/did-core-test-server/suites/did-core-properties/default.js
packages/did-core-test-server/suites/did-identifier/default.js
packages/did-core-test-server/suites/did-production/default.js
packages/did-core-test-server/suites/implementations/did-trust.json

This adds the [did:trust DID method](https://github.com/w3c/did-spec-registries/pull/297) to the did-test-suite for the DID method test suites:
- did-consumption
- did-core-properties
- did-identifier
- did-production
This PR relies on PR #101 in order to pass DID syntax tests.

Add did:trust DID Method to the did-test-suite

---

packages/did-core-test-server/suites/did-core-properties/did-core-properties.js
packages/jest-did-matcher/src/matchers/toBeMultibaseString/index.js
packages/jest-did-matcher/src/matchers/toBeMultibaseString/index.test.js
packages/jest-did-matcher/src/matchers/toBeMultibaseString/predicate.js

This PR is in support of addressing https://github.com/w3c/did-core/issues/707 via PRs https://github.com/w3c-ccg/security-vocab/pull/103, https://github.com/w3c/did-spec-registries/pull/299, and https://github.com/w3c/did-core/issues/731 based on the plan put forth in https://github.com/w3c/did-core/issues/707#issuecomment-826382717.
It should be merged last, after all the other PRs have been merged.

Add support for publicKeyMultibase.

---

packages/did-core-test-server/package.json
packages/did-core-test-server/suites/did-consumption/did-json-consumption.js
packages/did-core-test-server/suites/did-consumption/did-jsonld-consumption.js
packages/did-core-test-server/suites/did-production/did-json-production.js
packages/did-core-test-server/suites/did-production/did-jsonld-production.js
packages/did-core-test-server/suites/did-production/did-producer.js

Jest's [toEqual](https://jestjs.io/docs/expect#toequalvalue) matcher checks object deep equality. This PR removes the `deep-equal` dependency in favor of using the Jest matcher which may be slightly more idiomatic.

Use jest toEqual instead of deep-equal

---

packages/did-core-test-server/suites/did-consumption/default.js
packages/did-core-test-server/suites/did-core-properties/default.js
packages/did-core-test-server/suites/did-identifier/default.js
packages/did-core-test-server/suites/did-production/default.js
packages/did-core-test-server/suites/implementations/did-unisot.json

Added the did:unisot DID method for the following suites:
- did-consumption
- did-core-properties
- did-identifier
- did-production

Add did:unisot DID Method to the did-test-suite

---

packages/did-core-test-server/suites/did-core-properties/did-metadata-structure.js

- Adderssing issue #112:
eliminating remaing function call to `didMetadataStructureTest_r`

Fixing DID Metadata structure test

---

packages/did-core-test-server/suites/did-core-properties/did-metadata-structure.js
packages/jest-did-matcher/README.md
packages/jest-did-matcher/src/matchers/toBeDidDocumentMap/index.js
packages/jest-did-matcher/src/matchers/toBeDidDocumentMap/index.test.js
packages/jest-did-matcher/src/matchers/toBeDidDocumentMap/predicate.js
packages/jest-did-matcher/src/matchers/toBeDidDocumentPropertyValueType/index.js
packages/jest-did-matcher/src/matchers/toBeDidDocumentPropertyValueType/index.test.js
packages/jest-did-matcher/src/matchers/toBeDidDocumentPropertyValueType/predicate.js

This is a follow-up PR that addresses issues mentioned in Issue #112 to support the test of multi-level map structure in DID Metadata tests using the new `toBeDidDocumentMap` matcher.
It passes most of the tests in the `did-core-properties` test suite for `did:orb` mentioned in PR #117.

Addresses metadata test failure on Issue #112

---

packages/did-core-test-server/suites/did-core-properties/did-core-properties.js

This relates to the issue described in PR #120.
Relative DID URL not accepted for the id of verificatiomMethod.
Due to spec, it should support both absolute and relative.
``
The value of the id property for a verification method MUST be a string that conforms to the rules in Section § 3.2 DID URL Syntax.
``

Verification method to accept relative DID URL

---

packages/did-core-test-server/suites/did-consumption/default.js
packages/did-core-test-server/suites/did-core-properties/default.js
packages/did-core-test-server/suites/did-identifier/default.js
packages/did-core-test-server/suites/did-production/default.js
packages/did-core-test-server/suites/implementations/did-lit.json

Adding the did:lit DID method for the following suites:
- did-identifier
- did-core-properties
- did-production
- did-consumption

Add did:lit DID Method to the did-test-suite

---

packages/jest-did-matcher/src/matchers/toBeValidDidUrl/index.test.js
packages/jest-did-matcher/src/matchers/toBeValidDidUrl/predicate.js

While reviewing PRs, I reviewed my code again, found the following hard-to-find bugs (sigh).
FIx to the first two errors revealed another error in the code while testing these fixed matchers with the did core test suites.
Luckily, the current tests pass as same as before applying this fix.
> did-core-test-server: Test Suites: 6 failed, 6 total
> did-core-test-server: Tests:       17 failed, 38 todo, 3200 passed, 3255 total
*** Please don't forget to `lerna run prepare` ***
---
This patch fixes multiple significant bugs in the predicate function.
- Missing multiple `+` in string concatenation of the regexp.
Lack of `+` nullifies the effect of `$` anchor.
This bug effectively forces the following three bugs
to be invisible from the matcher's own tests:
- Path segment couldn't repeat.
- …

Fix to regexp of predicate function of toBeValidDidUrl

---

package.json

This is useful to prevent people from encountering the same issues as what @Diiaablo95 found in issue #99

chore: sets the base node engine to V14 or greater

---

packages/did-core-test-server/suites/did-resolution/default.js
packages/did-core-test-server/suites/did-url-dereferencing/default.js
packages/did-core-test-server/suites/implementations/dereferencer-web-transmute.json

This PR makes use of a couple rarely used did core feature:
- service
- relativeRef
- dereference (with non did core content type, in this case typescript)
The example is pulled from this did package manager for the deno programing language:
https://github.com/OR13/deno-did-pm
since deno uses URLs for modules, any deno module can be represented as a DID URL on a web origin that supports did dereferencing.
The same is likely true of GoLang as well.

Add deno-did-pm dereference example

---

packages/did-core-test-server/suites/did-core-properties/did-metadata-structure.js

As discussed in #65, removed `todo` for the following statement:
7.3 Metadata Structure - All metadata property definitions
registered in the DID Specification Registries
[DID-SPEC-REGISTRIES] MUST define the value type,
including any additional formats or restrictions to
that value (for example, a string formatted as a date
or as a decimal integer).

Removing `todo` test in Sec. 7.3

---

packages/did-core-test-server/suites/did-consumption/default.js
packages/did-core-test-server/suites/did-core-properties/default.js
packages/did-core-test-server/suites/did-identifier/default.js
packages/did-core-test-server/suites/did-production/default.js
packages/did-core-test-server/suites/did-resolution/default.js
packages/did-core-test-server/suites/implementations/did-key-mattr.json
packages/did-core-test-server/suites/implementations/did-sov-mattr.json
packages/did-core-test-server/suites/implementations/did-web-mattr.json
packages/did-core-test-server/suites/implementations/resolver-mattr-key.json
packages/did-core-test-server/suites/implementations/resolver-mattr-sov.json
packages/did-core-test-server/suites/implementations/resolver-mattr-web.json

Working did and resolver implementations for MATTR libraries we use internally. Dereferencing is going to come separately because I expect it will introduce some potentially controversial changes related to issue #129.

feat: add support for MATTR did and resolver implementations

---

packages/jest-did-matcher/src/matchers/toBeValidDid/index.test.js
packages/jest-did-matcher/src/matchers/toBeValidDid/predicate.js

Relates to comments in PR #101
- Adding more tests
- Replacing one regex with two simpler regexps.

Allowing tailng pct-encoded method-specific-id

---

packages/did-core-test-server/suites/did-resolution/did-resolution.js
packages/did-core-test-server/suites/did-url-dereferencing/did-url-dereferencing.js
packages/did-core-test-server/suites/did-url-dereferencing/did-url-dereferencing.spec.js

This is a small fix for the dereferencing test suite which shouldn't affect any of the existing reports.

Small bugfix in dereferencing tests.

---

packages/did-core-test-server/suites/did-resolution/default.js
packages/did-core-test-server/suites/did-url-dereferencing/default.js
packages/did-core-test-server/suites/implementations/universal-resolver-dereferencer-tests.json
packages/did-core-test-server/suites/implementations/universal-resolver-resolver-tests.json

Some additional reports from the Universal Resolver, generated using code here: https://github.com/decentralized-identity/universal-resolver/tree/peacekeeper-w3c-testsuite/examples/src/main/java/uniresolver/examples/w3ctestsuite
This should cover a few more spec statements that so far have insufficient implementations.

Add more Universal Resolver reports.

---

packages/did-core-test-server/suites/did-consumption/default.js
packages/did-core-test-server/suites/did-core-properties/default.js
packages/did-core-test-server/suites/did-identifier/default.js
packages/did-core-test-server/suites/did-production/default.js
packages/did-core-test-server/suites/did-resolution/default.js
packages/did-core-test-server/suites/did-url-dereferencing/default.js
packages/did-core-test-server/suites/implementations/dereferencer-polygon-ayanworks.json
packages/did-core-test-server/suites/implementations/did-polygon-ayanworks.json
packages/did-core-test-server/suites/implementations/resolver-polygon-ayanworks.json

This request is to add test suite implementation for Polygon DID by AyanWorks.
Files added:
- did-polygon-ayanworks.json
- resolver-polygon-ayanworks.json
- derefrencer-polygon-ayanworks.json
Files edited:
packages/did-core-test-server/suites/did-consumption/default.js
packages/did-core-test-server/suites/did-core-properties/default.js
packages/did-core-test-server/suites/did-identifier/default.js
packages/did-core-test-server/suites/did-production/default.js
packages/did-core-test-server/suites/did-resolution/default.js
packages/did-core-test-server/suites/did-url-dereferencing/default.js
All the test cases pass on execution for above implementation. Please find the screenshot attached.

Added Polygon-DID implementation Test Suites

---

packages/did-core-test-server/suites/did-resolution/did-resolution.js

This comments out some tests that are interesting but are not actually based on normative statements in the specification. Those can potentially be added back in the future once there are more implementations.
This PR also improves the description strings of some tests, so it's clear which property a test is testing.

Deactivate tests that are not actually based on normative statements.

---

packages/did-core-test-server/suites/implementations/dereferencer-web-transmute.json
packages/did-core-test-server/suites/implementations/did-key-transmute.json
packages/did-core-test-server/suites/implementations/did-web-transmute.json

@msporny I attempted to update our examples to get things to render better.
The dereference tests were not parsing the didUrls, so adding examples of did params to our `did:web` implementation uncovered bugs that the dereference tests by themselves did not catch.
This suggestions that we really ought to either:
1. update the dereference tests so they fail when did url parsing fails.
2.  require implementers to submit ALL did url examples they use in `resolve or dereference fixtures` in their `did implementation fixture`
I took the option 2 approach, here... IMO, option 1 would be better.
cc @peacekeeper

Update transmute implementation fixtures

---

packages/did-core-test-server/suites/implementations/dereferencer-mattr.json
packages/did-core-test-server/suites/implementations/did-key-mattr.json
packages/did-core-test-server/suites/implementations/did-sov-mattr.json
packages/did-core-test-server/suites/implementations/did-web-mattr.json

Updates our implementations to add support for JSON and move the didParameters into our dereferencer report instead of the did syntax report. As far as I can tell this should address all of the JSON features now and should make all of the syntax tests pass for every query parameter even though our dereferencer doesn't support every query parameter.

feat: update report for MATTR implementations

---

packages/did-core-test-server/suites/did-consumption/default.js
packages/did-core-test-server/suites/did-core-properties/default.js
packages/did-core-test-server/suites/did-identifier/default.js
packages/did-core-test-server/suites/did-production/default.js
packages/did-core-test-server/suites/implementations/did-ebsi.json

This adds an implementation report for `did:ebsi`. It was generated using libraries and APIs from the [EBSI](https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/EBSI) Early Adopter program. 
Generating this report did NOT use any parts of the DIF Universal Resolver (even though that also supports `did:ebsi`).

Add implementation of did:ebsi method.

---

packages/did-core-test-server/report/report-template.html

The PR changes text that says `Conformance Report` to say `Implementation Report`

Change 'conformance report' to 'implementation report'

---

packages/did-core-test-server/report/report-template.html

This PR attempts to address a ReSpec warning about a missing conformance section.

Add conformance section

---

packages/did-core-test-server/suites/implementations/did-pkh-spruce.json

Fix use of `blockchainAccountId` in the `did:pkh` implementation added in #185.
Corresponding source code change: https://github.com/spruceid/ssi/pull/230

Update did-pkh-spruce implementation

---

packages/did-core-test-server/suites/did-production/did-json-production.js

I think the if statement for integer vs double test is wrong
example: 
[did-web-mattr.json](https://github.com/w3c/did-test-suite/blob/829312ab92badc94ce68e29e043151326140345d/packages/did-core-test-server/suites/implementations/did-web-mattr.json#L67) provides: `"ranking": 4.5`
* current result: [integer test passes](https://w3c.github.io/did-test-suite/#T43)
* expected result: [double test should pass](https://w3c.github.io/did-test-suite/#T42)

fix integer vs double test

---

packages/did-core-test-server/suites/did-production/default.js
packages/did-core-test-server/suites/did-production/did-jsonld-production.js
packages/did-core-test-server/suites/utils.js

This PR is an attempt to upgrade the DID test suite to support v1.1 (which uses a separate context entry). The purpose here is to effectively duplicate all existing implementations, upgrading them to support v1.0 and v1.1 DID Documents. This PR proves that approach to be viable. 
We might also choose to do JSON-LD canonicalization on the v1.1 documents to ensure they canonicalize to the same values as v1.0.

Implement DID v1.1 tests.
