packages/did-core-test-server/package.json, packages/did-core-test-server/suites/did-spec/default.json, packages/did-core-test-server/suites/did-spec/defaultSuiteConfig.json, packages/did-core-test-server/suites/did-spec/did-core-properties.js, packages/did-core-test-server/suites/did-spec/did-jsonld-production.js, packages/did-core-test-server/suites/did-spec/did.spec.js
This PR partially addresses #27.
=> Add JSON-LD Production tests.

packages/did-core-test-server/suites/did-spec/did-jsonld-consumption.js, packages/did-core-test-server/suites/did-spec/did.spec.js
=> Add JSON-LD Consumption tests.

packages/did-core-test-server/suites/did-spec/defaultSuiteConfig.json, packages/did-core-test-server/suites/did-spec/did-consumer.js, packages/did-core-test-server/suites/did-spec/did.spec.js
=> Test Conforming Consumer

packages/did-core-test-server/package.json
Fixing minor glitch to make the whole test to pass
=> Adding missing node-jose to package.json

packages/did-core-test-server/suites/did-core-properties/default.js, packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/did-production/default.js, packages/did-core-test-server/suites/did-resolution/default.js, packages/did-core-test-server/suites/implementations/did-ethr-2021-consensys-mesh.json, packages/did-core-test-server/suites/implementations/resolver-ethr-consensys-mesh.json
Add did:ethr from ConsenSys Mesh
=> Add did:ethr from ConsenSys Mesh

packages/did-core-test-server/suites/did-core-properties/did-metadata-structure.js
Addresess Issue #56 for 7.3 Metadata Structure
=> Add a prefix to `it` block name to include "7.3 Metadata Structure"

packages/did-core-test-server/suites/did-core-properties/did-core-properties.js
Fix to pass test
This is a failure caused by my bad suggestion :<
=> Fix: toArray -> toBeArray

packages/did-core-test-server/suites/did-consumption/default.js, packages/did-core-test-server/suites/did-consumption/did-consumption.spec.js, packages/did-core-test-server/suites/did-consumption/did-jsonld-consumption.js, packages/did-core-test-server/suites/did-identifier/did-syntax.js, packages/did-core-test-server/suites/did-url-dereferencing/did-url-dereferencing.js
This PR adds tests to the test suite that were missing based on a review of issues #72 - #77.
=> Add remaining missing tests that came up during test suite audit.

packages/did-core-test-server/suites/did-consumption/default.js, packages/did-core-test-server/suites/did-core-properties/default.js, packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/did-production/default.js, packages/did-core-test-server/suites/implementations/did-v1-vof.json, packages/jest-did-matcher/src/matchers/toBeValidDid/predicate.js
This PR adds an implementation of did:v1 to the DID Core test suite.
=> Add implementation of did:v1.

packages/jest-did-matcher/src/matchers/toBeDidCoreDatetime/index.js, packages/jest-did-matcher/src/matchers/toBeDidCoreDatetime/index.test.js, packages/jest-did-matcher/src/matchers/toBeDidCoreDatetime/predicate.js
=> Slight improvement to DID Datetime matcher

packages/did-core-test-server/suites/did-consumption/default.js, packages/did-core-test-server/suites/did-core-properties/default.js, packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/did-production/default.js, packages/did-core-test-server/suites/implementations/did-monid.json
[monid DID method](https://github.com/lianxi-tech/monid) specification test according to the [GitHub thread](https://github.com/w3c/did-test-suite/issues/89).
We will submit another PR for did resolver in a couple of days.
=> add "did:monid" to did-test-suite

packages/did-core-test-server/suites/did-consumption/default.js, packages/did-core-test-server/suites/did-core-properties/default.js, packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/did-production/default.js, packages/did-core-test-server/suites/implementations/did-vaa.json
Added the vaa DID method for the following suites:
did-consumption
did-core-properties
did-identifier
did-production
=> Add did:vaa DID Method to the did-test-suite

packages/did-core-test-server/suites/did-consumption/default.js, packages/did-core-test-server/suites/did-core-properties/default.js, packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/did-production/default.js, packages/did-core-test-server/suites/implementations/did-orb.json
list of did samples:
- did:orb:interim:EiDHdXhNm7LuCqxo4JvAwKYKiFmpf85YFswAovxTxI_y4Q (interim did, local cas, V1 CID, P-256 JsonWebKey2020, empty service)
- did:orb:bafkreiazah4qrybzyapmrmk2dhldz24vfmavethcrgcoq7qhic63zz55ru:EiAag4cmgxAE2isL5HG3mxjS7WRq4l-xyyTgULCAcEHQQQ (canonical did, local cas, V1 CID, P-256 JsonWebKey2020, empty service)
- did:orb:bafkreihp4inweep4py7gw4j7hej5mqlbwa7br4u7mtrfxr5khfwpu3qu3m:EiB2tmdM_oWwjXj6AmVLm0RFa_8XKZHipOpNGpEODIVN8Q (canonical did, local cas, V1 CID, ed25519 Ed25519VerificationKey2018, DIDComm v1 service)
- did:orb:bafkreibcsubh3ifub7gletz27hcdyhwvrhlh5mwfth2m5fbasqua6yalay:EiA2ZtZqXjKZt-yf19ersmaCYm-gJEnlixrfk0Mi61ETTg (canonical did, local cas, V1 CID, P-256 JsonWebKey2020, DIDComm v2 service)
- …
=> chore: add orb did

README.md, packages/did-core-test-server/README.md, packages/jest-did-matcher/src/matchers/toBeAsciiString/index.js, packages/jest-did-matcher/src/matchers/toBeBase58String/index.js, packages/jest-did-matcher/src/matchers/toBeDidCoreDatetime/index.js, packages/jest-did-matcher/src/matchers/toBeDidDocumentPropertyValueType/index.js, packages/jest-did-matcher/src/matchers/toBeInfraMap/index.js, packages/jest-did-matcher/src/matchers/toBeInfraString/index.js, packages/jest-did-matcher/src/matchers/toBeMediaType/index.js, packages/jest-did-matcher/src/matchers/toBeMultibaseString/index.js, packages/jest-did-matcher/src/matchers/toBeValidDid/index.js, packages/jest-did-matcher/src/matchers/toBeValidDidUrl/index.js, packages/jest-did-matcher/src/matchers/toBeValidDidUrl/index.test.js, packages/jest-did-matcher/src/matchers/toBeValidUri/index.js, packages/jest-did-matcher/src/matchers/toBeValidUrl/index.js
Also,
- Added a test case to DID URL matcher.
- Added some description to README when observing errors.
=> Jest-did-matcher matcher message cleanup

packages/did-core-test-server/suites/did-resolution/default.js, packages/did-core-test-server/suites/implementations/resolver-did-orb.json, packages/did-core-test-server/suites/resolution-utils.js
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
=> WIP chore: add orb resolution

packages/did-core-test-server/suites/implementations/resolver-did-orb.json, packages/did-core-test-server/suites/resolution-utils.js
- Fixed the check to compare the did method name for equivalentId and canonicalId.
Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>
=> chore: add orb resolution

package.json, packages/did-core-test-server/report/report-generator/generateImplementationSummary.js, packages/did-core-test-server/report/report-generator/recursiveRenderSection.js, packages/did-core-test-server/report/report-template.html
Also fixing `generate-test-data` entry in  top-level `package.json`
=> Move stylesheets to the report template to eliminate duplication

packages/did-core-test-server/report/generate-report.js, packages/did-core-test-server/report/report-generator/generateDetailedReportByMethods.js, packages/did-core-test-server/report/report-generator/generateDetailedReportBySuites.js, packages/did-core-test-server/report/report-generator/generateImplementationSummary.js, packages/did-core-test-server/report/report-generator/generateSpecStatementSummary.js, packages/did-core-test-server/report/report-generator/recursiveRenderSection.js, packages/did-core-test-server/report/report-generator/tallyResults.js, packages/did-core-test-server/report/report-template.html
=> New section: Summary by Implementation by Spec Statements

packages/did-core-test-server/report/report-generator/recursiveRenderSection.js, packages/did-core-test-server/report/report-generator/tallyResults.js
This reverts commit 05e14756e20686304f4e890c827c0653b0eb3f86.
=> Revert "Eliminating tests with 'example' string from the report"

packages/did-core-test-server/routes/index.js
fixes https://github.com/w3c/did-test-suite/issues/142
=> Use type object instead of array for endpoint

.github/workflows/ci-include-breaking.yml, .gitignore, docs/README.md, packages/did-core-test-server/package.json
This PR fixes the CI failures while still allowing us to use the CI to confirm passing behavior for PRs.
It also adds CI report deployment.
=> Add CI Report Publishing

packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/implementations/universal-resolver-dereferencer-tests.json, packages/did-core-test-server/suites/implementations/universal-resolver-identifier-tests.json
Using code here: https://github.com/decentralized-identity/universal-resolver/tree/peacekeeper-w3c-testsuite/examples/src/main/java/uniresolver/examples/w3ctestsuite
=> Some additional test reports from Universal Resolver

packages/did-core-test-server/report/report-generator/generateDetailedReportByMethods.js, packages/did-core-test-server/report/report-generator/generateDetailedReportBySuites.js, packages/did-core-test-server/report/report-generator/generateImplementationSummary.js, packages/did-core-test-server/report/report-generator/generateSpecStatementSummary.js, packages/did-core-test-server/report/report-generator/recursiveRenderSection.js, packages/did-core-test-server/report/report-generator/tallyResults.js, packages/did-core-test-server/report/report-generator/updateSection.js, packages/did-core-test-server/report/report-template.html
- Using wider table style (100em) for readability
- In the report by methods section, all rows now with statement texts.
- Minor adjustments on stylesheets
- Added descriptions for clippings of longer strings
- Hyperlinks with statements.
=> Report generation improvement work 4

packages/did-core-test-server/suites/did-consumption/default.js, packages/did-core-test-server/suites/did-core-properties/default.js, packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/did-production/default.js, packages/did-core-test-server/suites/did-resolution/default.js, packages/did-core-test-server/suites/implementations/did-bid.json
update did-consumption/default.js
update did-core-properties/default.js
updata did-identifier/default.js
update did-production/default.js
update did-resolution/default.js
add implementations/did-bid.json
=> update did:bid test files

packages/did-core-test-server/suites/did-consumption/default.js, packages/did-core-test-server/suites/did-core-properties/default.js, packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/did-production/default.js, packages/did-core-test-server/suites/did-resolution/default.js, packages/did-core-test-server/suites/did-url-dereferencing/default.js, packages/did-core-test-server/suites/implementations/dereferencer-spruce-key.json, packages/did-core-test-server/suites/implementations/dereferencer-spruce-onion.json, packages/did-core-test-server/suites/implementations/dereferencer-spruce-pkh.json, packages/did-core-test-server/suites/implementations/dereferencer-spruce-tz.json, packages/did-core-test-server/suites/implementations/dereferencer-spruce-web.json, packages/did-core-test-server/suites/implementations/dereferencer-spruce-webkey.json, packages/did-core-test-server/suites/implementations/did-key-spruce.json, packages/did-core-test-server/suites/implementations/did-onion-spruce.json, packages/did-core-test-server/suites/implementations/did-pkh-spruce.json, packages/did-core-test-server/suites/implementations/did-tz-spruce.json, packages/did-core-test-server/suites/implementations/did-web-spruce.json, packages/did-core-test-server/suites/implementations/did-webkey-spruce.json, packages/did-core-test-server/suites/implementations/resolver-spruce-key.json, packages/did-core-test-server/suites/implementations/resolver-spruce-onion.json, packages/did-core-test-server/suites/implementations/resolver-spruce-pkh.json, packages/did-core-test-server/suites/implementations/resolver-spruce-tz.json, packages/did-core-test-server/suites/implementations/resolver-spruce-web.json, packages/did-core-test-server/suites/implementations/resolver-spruce-webkey.json
Test vectors/reports generated here: https://github.com/spruceid/didkit/pull/178
=> Add Spruce implementations

packages/did-core-test-server/suites/did-core-properties/default.js, packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/did-production/default.js, packages/did-core-test-server/suites/implementations/did-jnctn.json
A cleaner PR for did-jnctn with just the required additions.
=> cleaner changes

packages/did-core-test-server/suites/did-consumption/default.js, packages/did-core-test-server/suites/did-core-properties/default.js, packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/did-production/default.js, packages/did-core-test-server/suites/implementations/did-web-evernym.json
This is a report for a DID created internally at Evernym to demonstrate the use of alsoKnownAs.
=> Add Evernym did:web report

packages/did-core-test-server/report/report-template.html
This PR removes notice of unresolved issues from the Introduction section
=> remove resolved issues

packages/did-core-test-server/report/report-template.html
This PR swaps section 3.2 `Summary by Method Implementation` and section 3.3 `Summary by Specification Statements`
=> Swap 3.2 and 3.3

packages/did-core-test-server/report/report-template.html
This PR adds a brief executive summary to the beginning of the implementation report.
=> Add executive summary to Implementation Report

packages/did-core-test-server/suites/did-consumption/default.js, packages/did-core-test-server/suites/did-core-properties/default.js, packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/did-production/default.js, packages/did-core-test-server/suites/did-resolution/default.js, packages/did-core-test-server/suites/did-url-dereferencing/default.js, packages/did-core-test-server/suites/implementations/dereferencer-ssb.json, packages/did-core-test-server/suites/implementations/did-ssb.json, packages/did-core-test-server/suites/implementations/resolver-ssb.json
This adds a did:ssb implementation, as DID method, resolver, and dereferencer.
Source: https://git.scuttlebot.io/%25%2FMucHT86roxKEJxfXvqgiRlo2oq7qIN%2FsFNv%2BRqt7x4%3D.sha256
=> Add did:ssb implementation

packages/did-core-test-server/suites/did-url-dereferencing/did-url-dereferencing.js
=> Remove todo test for untestable statement

packages/did-core-test-server/suites/did-url-dereferencing/did-url-dereferencing.js
Reverts w3c/did-test-suite#196
=> Revert "Remove todo test for untestable statement"

packages/did-core-test-server/suites/implementations/universal-resolver-did-ebsi.json
Fixes https://github.com/w3c/did-test-suite/pull/205 failing tests
=> Fix DID EBSI method tests

packages/did-core-test-server/suites/did-consumption/default.js, packages/did-core-test-server/suites/did-core-properties/default.js, packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/did-production/default.js, packages/did-core-test-server/suites/did-resolution/default.js, packages/did-core-test-server/suites/did-url-dereferencing/default.js, packages/did-core-test-server/suites/implementations/dereferencer-art.json, packages/did-core-test-server/suites/implementations/did-art.json, packages/did-core-test-server/suites/implementations/universal-resolver-did-art.json
Create did:art method for art collection identity
=> add art method

packages/did-core-test-server/suites/did-consumption/default.js, packages/did-core-test-server/suites/did-core-properties/default.js, packages/did-core-test-server/suites/did-identifier/default.js, packages/did-core-test-server/suites/did-production/default.js, packages/did-core-test-server/suites/did-resolution/default.js, packages/did-core-test-server/suites/did-url-dereferencing/default.js, packages/did-core-test-server/suites/implementations/dereferencer-dxd.json, packages/did-core-test-server/suites/implementations/did-dxd.json, packages/did-core-test-server/suites/implementations/universal-resolver-did-dxd.json
Add a implementataion for Data-Alliance DID Method (dxd)
=> Add Data-Alliance DID Method - dxd
